name: Feature
description: Request or propose a change
title: "[Feature] <short title>"
labels: [atlas, p2, tshirt-s]
body:
  - type: markdown
    attributes:
      value: |
        Fill the sections. Keep it concise. Atlas will refine when label `atlas` is present and the issue is in Stage: Refinement.

  - type: textarea
    id: why
    attributes:
      label: Why
      description: Why this is needed
      placeholder: Short rationale
    validations:
      required: true

  - type: textarea
    id: what
    attributes:
      label: What
      description: What to change/add
      placeholder: Concrete change in one or two bullets
    validations:
      required: true

  - type: textarea
    id: out_of_scope
    attributes:
      label: Out of scope
      placeholder: Bullets of what is explicitly excluded
    validations:
      required: false

  - type: textarea
    id: draft_acs
    attributes:
      label: Draft ACs
      description: Acceptance criteria candidates
      placeholder: |
        - AC-1: ...
        - AC-2: ...
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Commands, versions, paths to touch, data/fixtures
      placeholder: |
        - Stack/versions:
        - Commands:
        - Paths to touch:
        - Data/fixtures:
    validations:
      required: true

  - type: checkboxes
    id: atlas
    attributes:
      label: Atlas
      description: Leave checked to trigger Atlas refinement
      options:
        - label: Ready for Atlas refinement
          required: true

  - type: markdown
    attributes:
      value: |
        <!--
        ATLAS:REFINE
        OUTPUT BLOCKS (post as a single comment on success)

        Prompt for Codex
        Context:
        - Repo(s): <org>/<repo>
        - Paths to touch: <paths>
        Goal:
        - <one sentence>
        Constraints:
        - <versions/tech constraints>
        Out of scope:
        - <bullets>
        Deliverables:
        - <bullets>
        Branch & PR:
        - branch: feature/<slug>

        Verification:
        - Run: <commands>
        - Expect: <observable checks>

        Acceptance Criteria
        AC-1: <behavior>; Verify: <steps, expected>
        AC-2: <behavior>; Verify: <steps, expected>
        AC-3: <behavior>; Verify: <steps, expected>

        Environment
        Branch pattern: feature/<slug>
        Preview URL: <if any>
        Secrets: <none|org secrets>
        Data: <seed script or fixtures>

        STATE RULES
        - If complete → Stage=Ready; add [ready, atlas-prepared]; remove [atlas, feedback-requested].
        - If incomplete → Stage=Backlog; add [feedback-requested]; comment missing info.
        -->
