name: Feature (Codex)
description: Prepare Codex-driven work
title: "[Feature] <short title>"
labels: [atlas, p2, tshirt-s]
body:
  - type: textarea
    id: goal
    attributes:
      label: Goal
      placeholder: Describe the desired outcome succinctly.
    validations:
      required: true
  - type: textarea
    id: acceptance_criteria
    attributes:
      label: Acceptance Criteria
      placeholder: |-
        - AC-1: ...
        - AC-2: ...
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment
      placeholder: |-
        - repo: .
        - language: <language/runtime>
        - commands: <build/test commands>
    validations:
      required: true
  - type: markdown
    attributes:
      value: |-
        <details>
        <summary>Atlas Instructions</summary>

        ```
        ATLAS:REFINE
        PURPOSE: Prepare this issue for execution by OpenAI Codex.
        OUTPUTS:
          - codex_prompt
          - acceptance_criteria
          - environment
        COMPLETE WHEN:
          - codex_prompt, acceptance_criteria, and environment are present and consistent.
        STATE:
          COMPLETE:
            MOVE: Ready
            ADD: [ready, atlas-prepared]
            REMOVE: [atlas, feedback-requested]
          INCOMPLETE:
            MOVE: Backlog
            ADD: [feedback-requested]
        REVIEW:
          PASS:
            MOVE: Done
          FAIL:
            MOVE: Ready
            ADD: [needs-fix]
        NOTES:
          - Use "refine" for Backlog→Ready.
          - Focus only on producing the Codex prompt; implementation follows separately.
        ```

        </details>
