name: Feature
description: Request or propose a change
title: "[Feature] <short title>"
labels: [atlas, p2, tshirt-s]
body:
  - type: textarea
    id: why
    attributes:
      label: Why
    validations:
      required: true

  - type: textarea
    id: what
    attributes:
      label: What
    validations:
      required: true

  - type: textarea
    id: draft_acs
    attributes:
      label: Draft ACs
      description: One per line, AC-1, AC-2, …
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Commands, versions, paths, data/fixtures
    validations:
      required: true

  # This block is invisible in the UI but persists in the issue body.
  - type: markdown
    attributes:
      value: |
        <!--
        ATLAS:REFINE
        OUTPUT BLOCKS (post as a single comment on success)

        Prompt for Codex
        Context:
        - Repo(s): <org>/<repo>
        - Paths to touch: <paths>
        Goal:
        - <one sentence>
        Constraints:
        - <versions/tech constraints>
        Out of scope:
        - <bullets>
        Deliverables:
        - <bullets>
        Branch & PR:
        - branch: feature/<slug>

        Verification:
        - Run: <commands>
        - Expect: <observable checks>

        Acceptance Criteria
        AC-1: <behavior>; Verify: <steps, expected>
        AC-2: <behavior>; Verify: <steps, expected>
        AC-3: <behavior>; Verify: <steps, expected>

        Environment
        Branch pattern: feature/<slug>
        Preview URL: <if any>
        Secrets: <none|org secrets>
        Data: <seed script or fixtures>

        STATE RULES
        - If complete → Stage=Ready; add [ready, atlas-prepared]; remove [atlas, feedback-requested].
        - If incomplete → Stage=Backlog; add [feedback-requested]; comment missing info.
        -->
